site_name: Build to Manage - Java application monitoring and logging lab
repo_url: https://github.com/rafal-szypulka/b2m-java
site_url: https://rafal-szypulka.github.io/b2m-java
nav:
    - 1. Introduction: index.md
    - 2. WLP logging and Elastic stack integration: logging.md
    - 3. Java application monitoring instrumentation: monitoring-instrumentation.md
    - 4. Prometheus and Grafana configuration: Prometheus-Grafana.md
    - 5. Deploy to IBM Cloud Private: ICP.md
theme:
  name: 'material'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
